# https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker image

on:
  push:
    branches:
      - master
      - feature/*
  # to allow to wait for a docker image to be published to proceed in another workflow
  workflow_call:
    # https://docs.github.com/en/actions/sharing-automations/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow
    inputs:
      image_tag_prefix:
        description: "Prefix for image tags (e.g., 'local-env-sha-')"
        required: false
        type: string
        default: ""
      cdn_enabled:
        description: "Enable CDN"
        required: false
        type: boolean
        default: true
      cdn_domain:
        description: "CDN domain"
        required: false
        type: string
        default: "cdn.chelzoo.tech"

jobs:
  push_to_registry:
    name: Push Docker image to Git Registry
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read
      attestations: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      # multi-platform build configured using this https://docs.docker.com/build/ci/github-actions/multi-platform/
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ghcr.io/tourmalinecore/${{ github.event.repository.name }}
          tags: |
            # minimal (short sha)
            type=sha${{ inputs.image_tag_prefix != '' && format(',prefix={0}', inputs.image_tag_prefix) || 'sha-' }}
            # full length sha
            type=sha,format=long${{ inputs.image_tag_prefix != '' && format(',prefix={0}', inputs.image_tag_prefix) || 'sha-' }}
            # set latest tag for default branch
            # https://github.com/docker/metadata-action/issues/171 explains how to tag latest only on default branch
            type=raw,value=${{ inputs.image_tag_prefix != '' ? format('{0}latest', inputs.image_tag_prefix) : 'latest' }},enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            CDN_ENABLED=${{ inputs.cdn_enabled }}
            CDN_DOMAIN=${{ inputs.cdn_domain }}