# https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker image for local-env

on:
  push:
    branches:
      - master
      - feature/*
  # to allow to wait for a docker image to be published to proceed in another workflow
  workflow_call:

jobs:
  push_to_registry:
    uses: ./.github/workflows/docker-build-and-push.yml
    with:
      image_tag_prefix: "local-env-"
      cdn_enabled: false
      cdn_domain: ""
    # without this it cannot login to the registry
    secrets: inherit