name: Publish Docker image for local-env

on:
  push:
    branches:
      - master
      - feature/*
  # to allow to wait for a docker image to be published to proceed in another workflow
  workflow_call:

jobs:
  push_to_registry:
    uses: TourmalineCore/pelican-github-workflows/.github/workflows/docker-build-and-push.yml@feature/build_and_push_workflow
    with:
        prefix: "local-env"
        build-args: |
          CDN_ENABLED=false
    # without this it cannot login to the registry
    secrets: inherit
