name: Publish Docker image for local-env

on:
  push:
    branches:
      - master
      - feature/*
  workflow_call:
  
jobs:
  push_to_registry:
    uses: TourmalineCore/pelican-github-workflows/.github/workflows/docker-build-and-push.yml@${{ github.head_ref || github.ref_name }}
    with:
        prefix: "local-env-"
        build-args: |
          CDN_ENABLED=false
    # without this it cannot login to the registry
    secrets: inherit
