name: Run playwright E2E tests
 
# ToDo should it be triggered only as part of an open PR?
# currently it triggers for any commit in a FB
on: 
  push:
    branches:
      - feature/*

jobs:
  # this is needed to wait for the new docker image to be build and published to the registry
  # so that we can use the image to run ui of the needed commit related version as part of local-env
  # the idea is taken from here https://stackoverflow.com/a/71489231
  push_to_registry:
    uses: ./.github/workflows/local-env-docker-build-and-push.yml
    # without this it cannot login to the registry
    secrets: inherit

  run-playwright-e2e-tests:
    needs: push_to_registry
    uses: TourmalineCore/pelican-github-workflows/.github/workflows/playwright-e2e-tests.yml@feature/playwright_e2e_tests_workflow
    with: 
      prefix: local-env
      path_to_values: deploy/values-ui.yaml.gotmpl
      deploy_env: |
       # this variable is used by local-env helmfile to use current feature branch helm chart values.yaml file
       # this is needed for a case when as part of the feature the chart was changed and is different from master branch
       # this should properly fill the feature branch name in spite of the pipeline trigger source (PR, commit, etc.)
       # https://stackoverflow.com/a/71158878
       PELICAN_UI_BRANCH=${{ github.head_ref || github.ref_name }}
      playwright_env: |
       FRONTEND_URL=http://localhost:40110 
       API_URL=http://localhost:40110/cms/api
