name: Publish Docker image for prod-env

on:
  push:
    branches:
      - master
      - feature/*

jobs:
  push_to_registry:
    uses: TourmalineCore/pelican-github-workflows/.github/workflows/docker-build-and-push.yml@feature/use_native_arm64_runners_without_emulation
    with:
        # Build-args used to define variables that will be used in image
        build-args: |
          CDN_ENABLED=true
          CDN_DOMAIN=cdn.chelzoo.ru
          CORS_ORIGIN=https://chelzoo.ru
          ENABLE_SEO_INDEXING=true
    # without this it cannot login to the registry
    secrets: inherit
