name: Check linting and run tests

on: 
  push:
    branches:
      - feature/*

jobs:
  check-lint:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [20.18.0]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Run CI command
      run: npm ci

    - name: Check linting
      run: npm run lint

  run-tests:
    runs-on: ubuntu-22.04
    needs: [check-lint]

    strategy:
      fail-fast: false
      matrix:
        node-version: [20.18.0]
        shardIndex: [1, 2, 3, 4, 5, 6]
        shardTotal: [6]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright component tests
      run: npx rimraf playwright/.cache && npx playwright test -c playwright-ct.config.ts --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: blob-report-${{ matrix.shardIndex }}
        path: blob-report
        retention-days: 1

  merge-reports:
    if: always() 
    runs-on: ubuntu-22.04 
    needs: [run-tests]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci
        
    - name: Download blob reports from GitHub Actions Artifacts
      uses: actions/download-artifact@v4
      with:
        path: all-blob-reports 
        pattern: blob-report-*
        merge-multiple: true
        
    - name: Merge into HTML Report
      run: npx playwright merge-reports --reporter html ./all-blob-reports 
        
    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      with:
        name: html-report--attempt-${{ github.run_attempt }}
        path: playwright-report
        retention-days: 1