name: Trigger Local And Prod Envs

on:
  push:
    branches:
      - feature/*

jobs:
  # this is needed to wait for the new docker image to be build and published to the registry
  # so that we can use the image to run ui of the needed commit related version as part of local-env
  # the idea is taken from here https://stackoverflow.com/a/71489231
  push_local_env_to_registry:
    uses: ./.github/workflows/local-env-docker-build-and-push.yml
    # without this it cannot login to the registry
    secrets: inherit

  push_prod_env_to_registry:
    uses: ./.github/workflows/prod-env-docker-build-and-push.yml
    secrets: inherit

  trigger_local_env:
    needs: push_local_env_to_registry
    uses: TourmalineCore/pelican-github-workflows/.github/workflows/sync-envs.yml@feature/separate_image_tag
    with: 
      pelican-env: pelican-local-env
      prefix: local-env
      path-to-values: deploy/values-ui.yaml.gotmpl
    secrets: inherit

  trigger_prod_env:
    needs: push_prod_env_to_registry
    uses: TourmalineCore/pelican-github-workflows/.github/workflows/sync-envs.yml@feature/separate_image_tag
    with: 
      pelican-env: pelican-prod-env
      path-to-values: deploy/values-ui.yaml.gotmpl
    secrets: inherit
