name: Trigger Local Env

on:
  push:
    branches:
      - master 

jobs:
  Trigger_Local_Env:
    runs-on: ubuntu-24.04
    steps: 
      - name: Trigger Local Env
        run: |
          curl -X POST https://api.github.com/repos/TourmalineCore/pelican-ui/pelican-local-env/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -u ${{ secrets.PELICAN_ENV_SYNC_TRIGGER_TOKEN }} \
          -d '{"event_type": "latest-ui-image-tag", "client_payload": {"sha": "${{ github.sha }}", "commit_message": "${{ github.event.head_commit.message }}"}}' 